---
apiVersion: v1
kind: Pod
metadata:
  name: worker-007
spec:
  nodeName: aa
  containers:
  - name: clockwork
    image: clockwork:local
    imagePullPolicy: "Never"
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: azure-functions-volume
      mountPath: "/azure-functions" 
    - name: clockwork-modelzoo-volta-volume
      mountPath: "/clockwork-modelzoo-volta" 
    - name: logs-volume
      mountPath: "/logs"     
    - name: shm-volume
      mountPath: "/dev/shm"
    securityContext:
      capabilities:
        add: ["SYS_RESOURCE"]
  volumes:
  - name: azure-functions-volume
    hostPath:
      path: /home/hzq/azure-functions
      type: DirectoryOrCreate
  - name: clockwork-modelzoo-volta-volume
    hostPath:
      path: /home/hzq/clockwork-modelzoo-volta
      type: DirectoryOrCreate
  - name: logs-volume
    hostPath:
      path: /home/hzq/logs
      type: DirectoryOrCreate 
  - name: shm-volume
    hostPath:
      path: /dev/shm
      
  restartPolicy: Never